default: &default
  adapter: postrgesql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: payment_service
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: payment_service
  pool: 5
  timeout: 5000
